"""T1 M-B — goal-stagnation actionization (v3 frozen: owner 5957186797 / 5957981558).

M-B lets a character, whose highest-priority staged goal is stuck on a *relational*
stage whose prerequisite is structurally missing, surface a single intermediate
recovery candidate from the EXISTING action space (e.g. ``contact_person`` under
a stuck ``successful_help`` stage). The candidate id carries an ``mb:`` provenance
token so downstream layers can (a) recognize the first real recovery event and
(b) suppress same-form re-generation within the same stagnation instance.

Frozen invariants this module upholds (no exceptions):
- No timers, no tick-based fallback, no attempt/state counters, no random
  injection.
- No ``rest`` fallback, no Store-1 special path.
- The candidate flows through the ordinary
  candidate -> scoring -> decision -> event pipeline (never bypassed).
- The token is a provenance/suppression marker only: it is not a new action
  type, it does not extend the action_type enum, and old events without a
  token keep the old parsing (no backfill, no guessing).
- Location-based stage prerequisites are NOT M-B targets: M-B only actionizes
  relational prerequisites.

M-C (stagnation predicate, owner 5957186797 §(b)): a goal is *structurally
stagnant* when it is the highest-priority active staged goal, its current stage
carries a relational prerequisite, the recovery target is present and co-located,
AND the recovery target has *no* reconciliation desire (a cold, deadlocked
target — the only state that distinguishes a true stagnation from a live
relationship where the target is still reachable/active). That last clause is a
pure read of the target's desire map: no timer, no tick count, no counter.
"""

from __future__ import annotations

from .action_types import canonical_action_type
from .models import ActionCandidate, CharacterState, WorldState

# Prefix for the provenance token carried in a fallback candidate id.
_T1_TOKEN = "mb"

# Relational stage prerequisites M-B can actionize, mapped to the existing
# action type that works *toward* the prerequisite.
# ``successful_help`` -> ``contact_person`` (NOT ``help_person``): the terminal
# help action requires a distressed target; the intermediate recovery step is to
# contact the target first (an existing, non-distress-gated action).
_RELATIONAL_FALLBACKS: dict[str, str] = {
    "target_same_location": "search_person",
    "successful_contact": "contact_person",
    "successful_help": "contact_person",
}


def _stagnation_goal(character: CharacterState):
    """Highest-priority active staged goal, or None."""
    goal = max(
        (g for g in character.goals if g.status == "active"),
        key=lambda g: g.priority,
        default=None,
    )
    if goal is None or not goal.stage_conditions:
        return None
    if goal.current_stage >= len(goal.stage_conditions):
        return None
    return goal


def _fallback_condition(cond: dict) -> tuple[str, str] | None:
    """Return (recovery_action_type, target_id) for a relational stage
    prerequisite, or None for location-based / non-M-B prerequisites."""
    action_type = _RELATIONAL_FALLBACKS.get(cond.get("type"))
    target = cond.get("target_id")
    if action_type is None or target is None:
        return None
    return action_type, target


def _mb_suppressed(state: WorldState, goal_id: str, stage: int, action_type: str, target_id: str) -> bool:
    """Same-form suppression: True when the event log already holds a
    *successful* ``mb:``-tokened event for the same stagnation instance
    (``goal.id + stage + action_type + target`` all match). Pure structure on
    ``causes[0]`` — no timer, no counter. Old (untokened) events are ignored."""
    prefix = f"{_T1_TOKEN}:{goal_id}:{stage}:{action_type}:{target_id}:"
    for event in state.event_log:
        if event.action_result is None or event.action_result.status != "success":
            continue
        c0 = event.causes[0] if event.causes else ""
        if c0.startswith(prefix):
            return True
    return False


def _stage_generable(state: WorldState, character: CharacterState) -> bool:
    """Frozen v3 T1-1 gate predicate (owner 5964978048: 'the current stage
    has no generable path') — implemented as the minimal executable check:
    the current (relational) stage has no path through the existing
    candidate-generation pipeline.

    Pipeline equivalence (owner: 'minimum executable check of the frozen
    predicate itself; no timer/counter/rest/random proxy'):

    For the stage's ``action_type`` ``A`` (from ``_RELATIONAL_FALLBACKS``)
    and its recovery target ``T`` (the stage's ``target_id``):

    An *ordinary* (untokened) generable path for stage ``A`` under target
    ``T`` exists iff the corresponding candidate is generated by
    ``generate_action_pool`` in the absence of a distress/emotional gate
    that would already be closed.  The existing pipeline is closed when:

      * ``T`` is not co-located  -> no ordinary contact/search candidate
      * the stage's motive (belonging / goal_motive) is zero or the
        ordinary threshold is not met  -> no contact candidate from the
        ordinary path
      * no distressed target exists in the pool that maps to ``A``

    In all three cases the pipeline returns *no* ordinary candidate for
    the stage's action type; the only remaining path is the M-B fallback
    itself.  This is read-only: it reuses the *same* generation logic as
    the ordinary path (same thresholds, same target selection, same
    motive computation) — no timer, no counter, no new threshold, no
    sorow/RNG proxy.
    """
    from .actions import _goal_supports_action, _trust

    goal = _stagnation_goal(character)
    if goal is None:
        return True  # no stage; gate not applicable (M-B returns None anyway)
    stage = goal.current_stage
    cond = goal.stage_conditions[stage]
    target_id = cond.get("target_id")
    if target_id is None:
        return True  # no relational target; M-B not applicable

    target = state.characters.get(target_id)
    if target is None:
        return True  # target absent; M-B not applicable

    # Same co-location check as the ordinary path.
    if target.location != character.location:
        return True  # not co-located: ordinary path cannot generate here

    # Ordinary path: the contact candidate fires when
    #   contact_pressure >= 20.0
    # where contact_pressure = max(relationship_motive, goal_motive)
    # and relationship_motive = max(reconciliation_motive, belonging * 0.50,
    #                                emotional_pressure)
    # Compute all terms exactly as generate_action_pool does.
    trust = _trust(state, character, target_id)
    tension = max(0.0, min(100.0,
                100.0 - trust,
                target.emotions.get("resentment", 0.0),
                target.emotions.get("fear", 0.0)))
    # relationship_motive
    reconciliation_motive = character.human_condition.desires.get("reconciliation", 0.0) * (tension / 100.0) ** 2
    belonging = character.human_condition.desires.get("belonging", 0.0)
    # AF: CONSUMED carrier zeroes belonging (lifecycle reader rule)
    carrier = character.desire_carriers.get("belonging")
    if carrier is not None and carrier.lifecycle == "CONSUMED":
        belonging = 0.0
    emotional_pressure = max(
        character.emotions.get("anger", 0.0),
        character.emotions.get("longing", 0.0),
        character.emotions.get("resentment", 0.0),
        character.emotions.get("love", 0.0),
    )
    relationship_motive = max(reconciliation_motive, belonging * 0.50, emotional_pressure)

    # goal_motive
    goal_motive = 100.0 * goal.priority if goal and _goal_supports_action(character, "contact_person") else 0.0

    contact_pressure = max(max(0.0, min(100.0, relationship_motive)), goal_motive)

    # If contact_pressure >= 20.0 the ordinary pipeline already generates a
    # contact_person candidate for this actor/target; M-B gate must stay
    # QUIET (no generable-path problem; ordinary path is alive).
    # If < 20.0 the ordinary path is closed — M-B gate fires.
    return contact_pressure < 20.0


def goal_stagnation_candidate(state: WorldState, character_id: str) -> ActionCandidate | None:
    """The single M-B recovery candidate for a structurally-stuck relational
    stage, tagged with the ``mb:`` provenance token; None otherwise.

    Gate (all must hold — structural only, no timers / counters / RNG):
      1. highest-priority active goal is staged on a relational stage,
      2. that stage's recovery target is present and co-located,
      3. the frozen v3 T1-1 gate: the current stage has NO generable path
         through the ordinary candidate-generation pipeline (minimal
         executable check of 'current stage has no generable path'),
      4. the same-form recovery is not already suppressed by a successful
         ``mb:`` event in the log.
    """
    character = state.characters[character_id]
    goal = _stagnation_goal(character)
    if goal is None:
        return None
    stage = goal.current_stage
    hit = _fallback_condition(goal.stage_conditions[stage])
    if hit is None:
        return None
    action_type, target_id = hit
    target = state.characters.get(target_id)
    if target is None:
        return None
    if target.location != character.location:
        return None
    # T1-1 frozen gate: current stage has no generable path (owner 5964978048).
    # Replaces the old cold-target discriminator (M-C proxy) with the
    # pipeline-derived predicate: read-only, same thresholds as the
    # ordinary path, no timer/counter/rest/random/sorrow proxy.
    if not _stage_generable(state, character):
        return None
    if _mb_suppressed(state, goal.id, stage, action_type, target_id):
        return None

    base_id = f"tick-{state.tick}-{character.id}-{action_type}"
    token_id = f"{_T1_TOKEN}:{goal.id}:{stage}:{action_type}:{target_id}:{base_id}"
    candidate = ActionCandidate(
        id=token_id,
        actor_id=character.id,
        action_type=action_type,
        targets=[target_id],
        motivation=f"work toward {goal.current_description}",
        preconditions=["target is co-located for the recovery step"],
        expected_outcomes=[f"make progress toward {goal.current_description}"],
        confidence=0.5,
        difficulty=0.0,
        score=0.15,
        metadata={
            "event_action_type": canonical_action_type(action_type),
            "world_validated": True,
            "mb_token": token_id,
        },
    )
    return candidate
